version: 2

project_name: genrify

before:
  hooks:
    - go mod tidy

builds:
  - id: genrify
    main: ./cmd/genrify
    binary: genrify
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X genrify/internal/buildinfo.Version={{.Version}}

archives:
  - id: default
    builds:
      - genrify
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: EysteinKS
    name: genrify-cli
